In [1]:
import os
import cv2
import numpy as np
from tensorflow.keras.models import load_model

In [6]:
new_model=load_model('/home/aayush/SudokuSolver/Saved models/Digit_Model_34.h5' )

In [7]:
images_dir='/home/aayush/Work@ayu/Projects/Digits2/'

In [8]:
images=os.listdir(images_dir)

In [9]:
predict_grid= np.zeros((9,9))

for image in images:
    imagec=image.split(".")[0][5:7]
    (x,y)=(int(imagec[0]),int(imagec[1]))
    my_image=cv2.imread(images_dir+image,0)
    my_image=cv2.resize(my_image,(28,28))
    my_image=np.array(my_image)
    my_image=255-my_image
    my_image=my_image/255
    my_image = np.expand_dims(my_image, axis=0)
    my_image = np.expand_dims(my_image, axis=0)
    my_image=my_image.reshape(1,28,28,1)
    predict_grid[x][y] = new_model.predict_classes(my_image, verbose=0)[0]
    
    org_img=cv2.imread(images_dir+image,1)

print(predict_grid)

[[3. 0. 0. 8. 0. 1. 0. 0. 1.]
 [2. 0. 1. 0. 3. 0. 8. 0. 4.]
 [0. 0. 0. 2. 0. 4. 0. 0. 0.]
 [8. 0. 9. 0. 0. 0. 1. 0. 8.]
 [0. 8. 0. 0. 0. 0. 0. 5. 0.]
 [7. 0. 2. 0. 0. 0. 4. 0. 9.]
 [0. 0. 0. 5. 0. 2. 0. 0. 0.]
 [9. 0. 4. 0. 8. 0. 7. 0. 5.]
 [6. 0. 0. 1. 0. 7. 0. 0. 3.]]
