In [3]:
import os
import cv2
import numpy as np
from tensorflow.keras.models import load_model

In [4]:
new_model=load_model('/home/aayush/SudokuSolver/Saved models/New_Digit_Model.h5' )

In [5]:
images_dir='/home/aayush/Work@ayu/Projects/Digits1/'

In [6]:
images=os.listdir(images_dir)

In [8]:
predict_grid= np.zeros((9,9))

for image in images:
    imagec=image.split(".")[0][5:7]
    (x,y)=(int(imagec[0]),int(imagec[1]))
    my_image=cv2.imread(images_dir+image,0)
    my_image=cv2.resize(my_image,(28,28))
    my_image=np.array(my_image)
    my_image=255-my_image
    my_image=my_image/255
    my_image = np.expand_dims(my_image, axis=0)
    my_image = np.expand_dims(my_image, axis=0)
    my_image=my_image.reshape(1,28,28,1)
    predict_grid[x][y] = new_model.predict_classes(my_image, verbose=0)[0]
    
    org_img=cv2.imread(images_dir+image,1)

print(predict_grid)

[[7. 7. 6. 7. 5. 7. 5. 7. 7.]
 [7. 7. 7. 7. 6. 7. 7. 6. 5.]
 [7. 7. 7. 7. 6. 5. 7. 5. 2.]
 [7. 7. 7. 7. 7. 5. 7. 6. 6.]
 [7. 3. 7. 7. 7. 5. 6. 5. 1.]
 [7. 7. 2. 7. 2. 1. 1. 1. 1.]
 [7. 7. 4. 7. 2. 1. 1. 1. 1.]
 [7. 1. 1. 9. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 2.]]
